name: Train workflow
on: [push]

permissions:
  contents: write
  pull-requests: write
  issues: write  

jobs:
  train:
    name: Train job
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Train model
        run: |
          python train.py > metrics.txt


      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Report" >> report.md
          cat metrics.txt >> report.md
          echo "### Confusion Matrix" >> report.md
          echo "![](plot.png)" >> report.md
          echo "### Feature importance" >> report.md
          echo "![](plot2.png)" >> report.md
          cml comment create report.md
